'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';

const seed=[
 {id:1,date:'2026-10-05',desc:'10 sessões de Fisioterapia',cat:'Fisioterapia',value:1300,payer:'Thais',supplier:'Jerfeson Arildo Pereira da Silva',status:'Pago',method:'PIX',proof:'Comprovante_20261005_132133.pdf'},
 {id:2,date:'2026-10-04',desc:'Dieta Enteral - Kit C/10 unidades',cat:'Dieta / Alimentação',value:34.28,payer:'Thais',supplier:'Nutri Life',status:'Pago',method:'Cartão',proof:''},
 {id:3,date:'2026-10-03',desc:'Pagamento 1ª semana cuidadora',cat:'Cuidadora',value:300,payer:'Thais',supplier:'Josane Silva de Paula',status:'Pago',method:'PIX',proof:'Comprovante_20261003_234457.pdf'},
 {id:4,date:'2026-10-02',desc:'Almofada ortopédica',cat:'Equipamentos',value:31.87,payer:'Thais',supplier:'KimiLife',status:'Pago',method:'Cartão',proof:''},
 {id:5,date:'2026-10-02',desc:'Papinha / itens de higiene',cat:'Medicamentos / Higiene',value:90.26,payer:'Thais',supplier:'Nutri Life',status:'Pago',method:'PIX',proof:''}
];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
const cats=['Cuidadora','Fisioterapia','Medicamentos / Higiene','Dieta / Alimentação','Equipamentos','Consultas','Exames','Transporte','Hospital / Clínica','Farmácia','Outros'];
function Icon({children}){return <span className="ico">{children}</span>}
export default function App(){
 const [session,setSession]=useState(null); const [authLoading,setAuthLoading]=useState(true); const [dataLoading,setDataLoading]=useState(false);
 const [page,setPage]=useState('Dashboard'); const [rows,setRows]=useState([]); const [query,setQuery]=useState(''); const [selected,setSelected]=useState(null); const [controle,setControle]=useState(null); const [notice,setNotice]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session?.user) loadData(); else {setRows([]);setControle(null)}},[session?.user?.id]);
 async function loadData(){setDataLoading(true);let {data:c}=await supabase.from('controles').select('*').order('created_at').limit(1).maybeSingle(); if(!c){const r=await supabase.from('controles').insert({user_id:session.user.id,nome:'Pai - Despesas'}).select().single();c=r.data} setControle(c); const {data,error}=await supabase.from('despesas').select('*').order('data',{ascending:false}).order('created_at',{ascending:false}); if(error)setNotice(error.message); else setRows((data||[]).map(dbToRow));setDataLoading(false)}
 async function saveExpense(f,file,stay=false){setDataLoading(true);let path=null,name=null;if(file){name=file.name;path=`${session.user.id}/${crypto.randomUUID()}-${safeName(file.name)}`;const up=await supabase.storage.from('comprovantes').upload(path,file,{contentType:file.type,upsert:false});if(up.error){setNotice('Falha no upload: '+up.error.message);setDataLoading(false);return false}}
  const payload={user_id:session.user.id,controle_id:controle?.id,data:f.date,descricao:f.desc,categoria:f.cat,valor:Number(f.value),pagador:f.payer,fornecedor:f.supplier,status:f.status,forma_pagamento:f.method,observacoes:f.notes||null,comprovante_path:path,comprovante_nome:name}; const {error}=await supabase.from('despesas').insert(payload);if(error){if(path)await supabase.storage.from('comprovantes').remove([path]);setNotice(error.message);setDataLoading(false);return false}else{setNotice('Despesa salva com sucesso.');await loadData();if(!stay)setPage('Despesas')}setDataLoading(false);return true}
 async function removeExpense(r){if(r.proofPath)await supabase.storage.from('comprovantes').remove([r.proofPath]);const {error}=await supabase.from('despesas').delete().eq('id',r.id);if(error)setNotice(error.message);else{await loadData();setPage('Despesas')}}
 async function openProof(r){if(!r.proofPath)return;const {data,error}=await supabase.storage.from('comprovantes').createSignedUrl(r.proofPath,60);if(error)setNotice(error.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 if(authLoading)return <div className="authPage"><div className="authCard"><h2>ContaClaraAI</h2><p>Carregando...</p></div></div>;
 if(!session)return <Auth/>;
 const total=rows.reduce((a,b)=>a+Number(b.value),0); const paid=rows.filter(x=>x.status==='Pago').reduce((a,b)=>a+Number(b.value),0); const pending=total-paid;
 const byCat=Object.entries(rows.reduce((a,r)=>{a[r.cat]=(a[r.cat]||0)+Number(r.value);return a},{})).sort((a,b)=>b[1]-a[1]); const nav=['Dashboard','Despesas','Comprovantes','Importar WhatsApp','Categorias','Pessoas','Relatórios'];
 return <div className="shell"><aside><div className="brand"><div className="logo">C</div><div><b>ContaClara<span>AI</span></b><small>Controle inteligente</small></div></div><div className="control"><small>CONTROLE ATUAL</small><b>{controle?.nome||'Pai - Despesas'}</b></div><nav>{nav.map((n,i)=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><Icon>{['⌂','▤','▣','◉','◇','♙','▥'][i]}</Icon>{n}</button>)}</nav><div className="user"><div className="avatar">{(session.user.email||'U').slice(0,2).toUpperCase()}</div><div><b>{session.user.email}</b><button className="link" onClick={()=>supabase.auth.signOut()}>Sair</button></div></div></aside>
 <main><header><div><h1>{page}</h1><p>{subtitle(page)}</p></div><div className="top"><select><option>Outubro 2026</option></select><button className="primary" onClick={()=>setPage('Nova despesa')}>＋ Nova despesa</button></div></header>{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice} ×</div>}{dataLoading&&<div className="loading">Sincronizando com Supabase...</div>}
 {page==='Dashboard'&&<Dashboard total={total} paid={paid} pending={pending} rows={rows} byCat={byCat} open={r=>{setSelected(r);setPage('Detalhe')}} add={()=>setPage('Nova despesa')}/>} 
 {page==='Despesas'&&<Expenses rows={rows} query={query} setQuery={setQuery} open={r=>{setSelected(r);setPage('Detalhe')}} add={()=>setPage('Nova despesa')}/>} 
 {page==='Nova despesa'&&<ExpenseForm save={saveExpense} cancel={()=>setPage('Despesas')}/>} 
 {page==='Detalhe'&&selected&&<Detail r={selected} back={()=>setPage('Despesas')} remove={()=>removeExpense(selected)} openProof={()=>openProof(selected)}/>} 
 {page==='Comprovantes'&&<Proofs rows={rows} openProof={openProof}/>} {page==='Importar WhatsApp'&&<WhatsApp saveExpense={saveExpense}/>} {page==='Categorias'&&<Categories byCat={byCat}/>} {page==='Pessoas'&&<People rows={rows}/>} {page==='Relatórios'&&<Reports total={total} rows={rows} byCat={byCat}/>} 
 </main></div>
}
function dbToRow(r){return {id:r.id,date:r.data,desc:r.descricao,cat:r.categoria,value:Number(r.valor),payer:r.pagador||'',supplier:r.fornecedor||'',status:r.status,method:r.forma_pagamento||'',proof:r.comprovante_nome||'',proofPath:r.comprovante_path||'',notes:r.observacoes||''}}
function safeName(n){return n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_')}
function Auth(){const [mode,setMode]=useState('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);async function go(e){e.preventDefault();setBusy(true);setMsg('');const res=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(res.error)setMsg(res.error.message);else if(mode==='signup'&&!res.data.session)setMsg('Cadastro criado. Verifique seu e-mail para confirmar a conta.');setBusy(false)}return <div className="authPage"><form className="authCard" onSubmit={go}><div className="brand authBrand"><div className="logo">C</div><div><b>ContaClara<span>AI</span></b><small>Controle inteligente</small></div></div><h2>{mode==='login'?'Entrar':'Criar conta'}</h2><p>Seus dados e comprovantes ficam protegidos por usuário.</p><Field l="E-mail"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field l="Senha"><input type="password" required minLength="6" value={password} onChange={e=>setPassword(e.target.value)}/></Field>{msg&&<div className="notice">{msg}</div>}<button className="primary wide" disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':'Cadastrar'}</button><button type="button" className="ghost wide" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Criar uma conta':'Já tenho uma conta'}</button></form></div>}

function subtitle(p){return ({Dashboard:'Acompanhe os gastos do controle em tempo real.',Despesas:'Visualize e gerencie todas as despesas.','Comprovantes':'Centralize os documentos vinculados aos lançamentos.','Importar WhatsApp':'Identifique possíveis despesas a partir de uma conversa exportada.',Categorias:'Organize os lançamentos por finalidade.',Pessoas:'Acompanhe quem realizou os pagamentos.',Relatórios:'Consolide a prestação de contas do período.','Nova despesa':'Registre uma nova despesa e seu comprovante.',Detalhe:'Confira todos os dados do lançamento.'})[p]||''}
function Cards({total,paid,pending,count}){return <div className="cards"><Card t="Total de despesas" v={money(total)} icon="▣"/><Card t="Pagas" v={money(paid)} icon="✓"/><Card t="A pagar" v={money(pending)} icon="◷"/><Card t="Lançamentos" v={count} icon="▤"/></div>}
function Card({t,v,icon}){return <div className="card metric"><div className="metricIcon">{icon}</div><div><small>{t}</small><strong>{v}</strong></div></div>}
function Dashboard({total,paid,pending,rows,byCat,open,add}){return <><Cards total={total} paid={paid} pending={pending} count={rows.length}/><div className="grid2"><div className="card"><h3>Despesas por categoria</h3><div className="chart"><div className="donut"><b>{money(total)}</b><small>Total</small></div><div className="legend">{byCat.slice(0,5).map(([c,v])=><div key={c}><span className="dot"></span><em>{c}</em><b>{money(v)}</b></div>)}</div></div></div><div className="card"><h3>Quem mais pagou</h3><div className="payer"><b>Thais</b><div><i style={{width:'94%'}}></i></div><strong>{money(paid)}</strong></div><div className="payer"><b>Outros</b><div><i style={{width:'4%'}}></i></div><strong>R$ 0,00</strong></div></div></div><div className="card tableCard"><div className="sectionTitle"><h3>Últimas despesas</h3><button className="primary" onClick={add}>＋ Nova despesa</button></div><Table rows={rows.slice(0,5)} open={open}/></div></>}
function Table({rows,open}){return <div className="table"><div className="tr th"><span>Data</span><span>Descrição</span><span>Categoria</span><span>Valor</span><span>Quem pagou</span><span>Status</span></div>{rows.map(r=><button className="tr" key={r.id} onClick={()=>open?.(r)}><span>{r.date.split('-').reverse().join('/')}</span><span><b>{r.desc}</b><small>{r.supplier}</small></span><span><label>{r.cat}</label></span><span><b>{money(r.value)}</b></span><span>{r.payer}</span><span><mark>● {r.status}</mark></span></button>)}</div>}
function Expenses({rows,query,setQuery,open,add}){const f=rows.filter(r=>(r.desc+r.cat+r.supplier).toLowerCase().includes(query.toLowerCase()));return <div className="card"><div className="toolbar"><input placeholder="Buscar descrição, fornecedor, categoria..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary" onClick={add}>＋ Nova despesa</button></div><Table rows={f} open={open}/></div>}
function ExpenseForm({save,cancel}){const [file,setFile]=useState(null); const [f,setF]=useState({desc:'',cat:'Fisioterapia',value:'',date:'2026-10-05',payer:'Thais',supplier:'',status:'Pago',method:'PIX',proof:'',notes:''}); const upd=(k,v)=>setF({...f,[k]:v});return <div className="formgrid"><div className="card"><h3>Dados da despesa</h3><div className="fields"><Field l="Descrição *"><input value={f.desc} onChange={e=>upd('desc',e.target.value)} placeholder="Ex.: 10 sessões de fisioterapia"/></Field><Field l="Categoria *"><select value={f.cat} onChange={e=>upd('cat',e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></Field><Field l="Valor *"><input value={f.value} onChange={e=>upd('value',e.target.value.replace(',','.'))} placeholder="1300,00"/></Field><Field l="Data *"><input type="date" value={f.date} onChange={e=>upd('date',e.target.value)}/></Field><Field l="Quem pagou?"><input value={f.payer} onChange={e=>upd('payer',e.target.value)}/></Field><Field l="Fornecedor / Recebedor"><input value={f.supplier} onChange={e=>upd('supplier',e.target.value)}/></Field><Field l="Forma de pagamento"><select value={f.method} onChange={e=>upd('method',e.target.value)}><option>PIX</option><option>Cartão</option><option>Dinheiro</option><option>Transferência</option></select></Field><Field l="Status"><select value={f.status} onChange={e=>upd('status',e.target.value)}><option>Pago</option><option>Pendente</option></select></Field></div><Field l="Observações"><textarea value={f.notes} onChange={e=>upd('notes',e.target.value)}/></Field></div><div className="card"><h3>Comprovante</h3><div className="upload"><b>⇧</b><strong>Selecione um comprovante</strong><small>PDF, JPG ou PNG</small><input type="file" accept=".pdf,image/*" onChange={e=>{const x=e.target.files?.[0]||null;setFile(x);upd('proof',x?.name||'')}}/></div>{f.proof&&<div className="file">📄 {f.proof}</div>}<button className="primary wide" disabled={!f.desc||!f.value} onClick={()=>save({...f,value:Number(f.value)},file)}>Salvar despesa</button><button className="ghost wide" onClick={cancel}>Cancelar</button></div></div>}
function Field({l,children}){return <label className="field"><span>{l}</span>{children}</label>}
function Detail({r,back,remove,openProof}){return <div className="formgrid"><div className="card"><button className="link" onClick={back}>← Voltar</button><h3>Informações da despesa</h3><dl>{[['Descrição',r.desc],['Categoria',r.cat],['Valor',money(r.value)],['Data',r.date.split('-').reverse().join('/')],['Quem pagou',r.payer],['Fornecedor',r.supplier],['Forma de pagamento',r.method],['Status',r.status]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl><button className="danger" onClick={remove}>Excluir lançamento</button></div><div className="card"><h3>Comprovante</h3>{r.proof?<div className="proofPreview"><div>COMPROVANTE</div><b>{money(r.value)}</b><small>{r.supplier}</small><small>{r.date}</small><p>✓ Pagamento efetivado</p><button className="primary wide" onClick={openProof}>Abrir comprovante</button></div>:<div className="empty">Nenhum comprovante anexado.</div>}</div></div>}
function Proofs({rows,openProof}){return <div className="proofgrid">{rows.map(r=><button className="card proof" key={r.id} onClick={()=>r.proofPath&&openProof(r)}><div className="doc">PDF</div><div><b>{r.proof||'Sem arquivo anexado'}</b><small>{r.desc}</small><strong>{money(r.value)}</strong></div></button>)}</div>}
function parseWhatsApp(text){
 const raw=text.replace(/\r/g,'').split('\n'); const msgs=[]; let cur=null;
 const re=/^\[(\d{1,2})\/(\d{1,2})\/(\d{2,4}),\s*(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?\]\s*(?:-\s*)?(?:([^:]+):\s*)?(.*)$/i;
 for(const line of raw){const m=line.match(re);if(m){if(cur)msgs.push(cur);let [,mo,da,yr,hh,mi,ss,ap,author,body]=m;let h=Number(hh);if(ap){if(ap.toUpperCase()==='PM'&&h<12)h+=12;if(ap.toUpperCase()==='AM'&&h===12)h=0}const y=Number(yr)<100?2000+Number(yr):Number(yr);cur={date:`${y}-${String(mo).padStart(2,'0')}-${String(da).padStart(2,'0')}`,time:`${String(h).padStart(2,'0')}:${mi}`,author:(author||'Sistema').trim(),text:(body||'').trim()}}else if(cur&&line.trim())cur.text+='\n'+line.trim()}if(cur)msgs.push(cur);return msgs
}
function brMoney(t){const m=t.match(/R\$\s*([\d.]+,\d{2})|(?:total\s*)?([\d.]+[,.]\d{2})/i);if(!m)return null;const v=(m[1]||m[2]).replace(/\./g,'').replace(',','.');const n=Number(v);return Number.isFinite(n)?n:null}
function classifyText(t){const x=t.toLowerCase();if(/fisioter/.test(x))return 'Fisioterapia';if(/cuidador|cuidadora/.test(x))return 'Cuidadora';if(/dieta|papinha|enteral/.test(x))return 'Dieta / Alimentação';if(/algod|álcool|alcool|luva|higiene|medic/.test(x))return 'Medicamentos / Higiene';if(/almofada|cadeira|equip/.test(x))return 'Equipamentos';return 'Outros'}
function analyzeWhatsApp(msgs){const out=[];const ignored=/criptografia|criou o grupo|mudou o nome|figurinha|mensagem apagada|obrigado|blz|fechado|vai mandando|vou criar um controle/i;for(let i=0;i<msgs.length;i++){const m=msgs[i];if(ignored.test(m.text))continue;const window=msgs.slice(i,Math.min(msgs.length,i+4)).filter(x=>x.date===m.date);const context=window.map(x=>x.text).join(' ');const proof=(context.match(/([\w.-]+\.pdf)/i)||[])[1]||'';const amount=brMoney(context);const meaningful=/fisioter|cuidador|cuidadora|dieta|papinha|algod|álcool|alcool|luva|higiene|medic|almofada|cadeira|equip|R\$/i.test(context);if(!meaningful&&!proof)continue;
 let desc='';for(const x of window){const clean=x.text.replace(/\[Encaminhada\]|<documento omitido>|<imagem ocultada>|\[Documento\]|\[Imagem\]/gi,'').replace(/[\w.-]+\.pdf/ig,'').trim();if(clean&&!/^segue o comprovante/i.test(clean)&&!/^R\$/i.test(clean)&&clean.length>3){desc=clean.split('\n')[0];if(/pagamento|fisioter|papinha|algod|dieta|almofada|equip/i.test(clean))break}}
 if(!desc)desc=proof?'Comprovante importado':'Despesa identificada';const cat=classifyText(context);let confidence=55+(proof?20:0)+(amount?15:0)+(cat!=='Outros'?10:0);confidence=Math.min(99,confidence);const key=[m.date,proof,amount,cat].join('|');if(out.some(x=>x.key===key))continue;out.push({key,date:m.date,desc,cat,value:amount||'',payer:m.author==='Sistema'?'':m.author,supplier:'',status:'Pago',method:proof?'PIX':'',proof,notes:`Importado do WhatsApp. Contexto: ${context.slice(0,700)}`,confidence,selected:!!amount})}return out}
function WhatsApp({saveExpense}){const [files,setFiles]=useState([]);const [step,setStep]=useState(1);const [messages,setMessages]=useState([]);const [candidates,setCandidates]=useState([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const txt=files.find(f=>f.name.toLowerCase().endsWith('.txt'));
 async function analyze(){if(!txt){setError('Selecione o arquivo .txt exportado pelo WhatsApp.');return}setBusy(true);setError('');try{const text=await txt.text();const parsed=parseWhatsApp(text);setMessages(parsed);setCandidates(analyzeWhatsApp(parsed));setStep(2)}catch(e){setError('Não foi possível ler o arquivo: '+e.message)}finally{setBusy(false)}}
 function upd(i,k,v){setCandidates(candidates.map((c,n)=>n===i?{...c,[k]:v}:c))}
 async function confirm(){const chosen=candidates.filter(c=>c.selected);if(!chosen.length){setError('Selecione pelo menos um lançamento para importar.');return}const invalid=chosen.find(c=>!Number(c.value)||Number(c.value)<=0);if(invalid){setError('Informe um valor válido para todos os lançamentos selecionados.');return}setBusy(true);setError('');try{for(const c of chosen){const media=files.find(f=>c.proof&&f.name===c.proof)||null;await saveExpense({...c,value:Number(c.value)},media,true)}setStep(3)}finally{setBusy(false)}}
 return <div className="card wa"><div className="steps"><b className={step===1?'current':''}>1 Upload do arquivo</b><b className={step===2?'current':''}>2 Análise das mensagens</b><b className={step===3?'current':''}>3 Conferência</b></div>{step===1&&<><div className="upload big"><b>◉</b><strong>Importar conversa do WhatsApp</strong><small>Selecione o chat.txt. Opcionalmente selecione também PDFs/imagens exportados para vinculá-los aos lançamentos.</small><input type="file" multiple accept=".txt,.pdf,image/*" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></div>{files.length>0&&<div className="analysis"><h3>Arquivos selecionados</h3><p><b>{txt?.name||'Nenhum .txt selecionado'}</b> · {files.length-Number(!!txt)} arquivo(s) de mídia</p><button className="primary" disabled={busy||!txt} onClick={analyze}>{busy?'Analisando...':'Analisar conversa'}</button></div>}</>}
 {step===2&&<div className="analysis wideAnalysis"><div className="reviewHead"><div><h3>Possíveis despesas encontradas</h3><p>{messages.length} mensagens lidas · {candidates.length} candidatos. Revise antes de gravar.</p></div><button className="ghost" onClick={()=>setStep(1)}>Trocar arquivo</button></div>{candidates.length===0?<div className="empty">Nenhuma despesa foi identificada automaticamente.</div>:candidates.map((c,i)=><div className={'candidate '+(c.selected?'selected':'')} key={c.key}><input className="check" type="checkbox" checked={c.selected} onChange={e=>upd(i,'selected',e.target.checked)}/><div className="candidateBody"><div className="candidateTop"><input value={c.desc} onChange={e=>upd(i,'desc',e.target.value)}/><mark>Confiança: {c.confidence}%</mark></div><div className="candidateFields"><Field l="Data"><input type="date" value={c.date} onChange={e=>upd(i,'date',e.target.value)}/></Field><Field l="Categoria"><select value={c.cat} onChange={e=>upd(i,'cat',e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select></Field><Field l="Valor"><input inputMode="decimal" placeholder="Obrigatório" value={c.value} onChange={e=>upd(i,'value',e.target.value.replace(',','.'))}/></Field><Field l="Pagador"><input value={c.payer} onChange={e=>upd(i,'payer',e.target.value)}/></Field></div>{c.proof&&<div className="matchedProof">📄 {c.proof} {files.some(f=>f.name===c.proof)?<span>arquivo encontrado</span>:<em>referência no chat; mídia não selecionada</em>}</div>}<details><summary>Ver contexto detectado</summary><pre>{c.notes.replace('Importado do WhatsApp. Contexto: ','')}</pre></details></div></div>)}<div className="reviewActions"><button className="primary" disabled={busy} onClick={confirm}>{busy?'Importando...':`Importar ${candidates.filter(c=>c.selected).length} selecionado(s)`}</button></div></div>}
 {step===3&&<div className="successImport"><div className="successIcon">✓</div><h3>Importação concluída</h3><p>Os lançamentos confirmados foram gravados no Supabase. Os comprovantes selecionados e encontrados pelo nome foram enviados ao Storage privado.</p><button className="primary" onClick={()=>{setStep(1);setFiles([]);setMessages([]);setCandidates([])}}>Nova importação</button></div>}{error&&<div className="notice">{error}</div>}</div>}

function Categories({byCat}){return <div className="categoryGrid">{cats.map(c=><div className="card category" key={c}><div className="catIcon">◇</div><div><b>{c}</b><small>{money(byCat.find(x=>x[0]===c)?.[1]||0)}</small></div></div>)}</div>}
function People({rows}){const sum=rows.reduce((a,r)=>{a[r.payer]=(a[r.payer]||0)+Number(r.value);return a},{});return <div className="categoryGrid">{Object.entries(sum).map(([p,v])=><div className="card category" key={p}><div className="avatar">{p.slice(0,2).toUpperCase()}</div><div><b>{p}</b><small>Total pago: {money(v)}</small></div></div>)}</div>}
function Reports({total,rows,byCat}){return <><Cards total={total} paid={total} pending={0} count={rows.length}/><div className="grid2"><div className="card"><h3>Prestação de contas por categoria</h3>{byCat.map(([c,v])=><div className="bar" key={c}><span>{c}</span><div><i style={{width:`${Math.max(5,v/total*100)}%`}}></i></div><b>{money(v)}</b></div>)}</div><div className="card"><h3>Resumo</h3><dl><div><dt>Lançamentos</dt><dd>{rows.length}</dd></div><div><dt>Com comprovante</dt><dd>{rows.filter(r=>r.proof).length}</dd></div><div><dt>Sem comprovante</dt><dd>{rows.filter(r=>!r.proof).length}</dd></div><div><dt>Total</dt><dd>{money(total)}</dd></div></dl><button className="primary wide" onClick={()=>window.print()}>Exportar / Imprimir PDF</button></div></div></>}
